version: "3"
services:
  nginx-geoip2:
    image: nginx-geoip2:latest
    container_name: nginx-geoip2
    hostname: nginx-geoip2
    build: .
    restart: always
    network_mode: bridge
    ports:
      - 80:80
      - 443:443
    volumes:
      - /opt/nginx:/etc/nginx/conf.d:ro
